### ISSUE TITLE
Service tendrl-node-monitoring failed

### ISSUE THREAD

**Issue by fbalak** [Tendrl/node-monitoring#7]
After successfully importing gluster trusted pool service tendrl-node-monitoring failed. Before that I tried to import gluster trusted pool with invalid data {"node_ids": ["000000-0000-0000-0000-000000000"],"sds_type": "gluster"}. Services tendrl-node-agent and tendrl-performance-monitoring are running.

`# systemctl status tendrl-node-monitoring`
```
● tendrl-node-monitoring.service - Daemon to manage tendrl node monitoring
   Loaded: loaded (/usr/lib/systemd/system/tendrl-node-monitoring.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2017-04-18 12:30:21 UTC; 1h 4min ago
 Main PID: 11058 (code=exited, status=1/FAILURE)

Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: complete.wait(timeout=1)
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: File "/usr/lib64/python2.7/site-packages/gevent/event.py", line 77, in wait
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: result = self.hub.switch()
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 331, in switch
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: return greenlet.switch(self)
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: NameError: global name 'Event' is not defined
Apr 18 12:30:21 hostname systemd[1]: tendrl-node-monitoring.service: main process exited, code=exited, status=1/FAILURE
Apr 18 12:30:21 hostname systemd[1]: Stopped Daemon to manage tendrl node monitoring.
Apr 18 12:30:21 hostname systemd[1]: Unit tendrl-node-monitoring.service entered failed state.
Apr 18 12:30:21 hostname systemd[1]: tendrl-node-monitoring.service failed.
```

excerpt from `#journalctl -u tendrl-node-monitoring`
```
...
Apr 18 12:26:03 hostname tendrl-node-monitoring[11058]: Finding atoms in namespace.tendrl.objects.Os.atoms
Apr 18 12:26:03 hostname tendrl-node-monitoring[11058]: Finding flows in namespace.tendrl.objects.Os.flows
Apr 18 12:26:03 hostname tendrl-node-monitoring[11058]: Registering object namespace.tendrl.objects.Platform
Apr 18 12:26:03 hostname tendrl-node-monitoring[11058]: Finding atoms in namespace.tendrl.objects.Platform.atoms
Apr 18 12:26:07 hostname python[11283]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 fbalak-usm1
Apr 18 12:26:08 hostname python[11297]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager dbpush
Apr 18 12:26:09 hostname python[11381]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arg
Apr 18 12:26:09 hostname python[11418]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active c
Apr 18 12:26:17 hostname python[11740]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 fbalak-usm1
Apr 18 12:26:18 hostname python[11748]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager memory
Apr 18 12:26:18 hostname python[11770]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arg
Apr 18 12:26:19 hostname python[11840]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active c
Apr 18 12:26:20 hostname python[11870]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 fbalak-usm1
Apr 18 12:26:21 hostname python[11914]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager collec
Apr 18 12:26:21 hostname python[11931]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arg
Apr 18 12:26:22 hostname python[11962]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active c
Apr 18 12:26:33 hostname python[12207]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 fbalak-usm1
Apr 18 12:26:34 hostname python[12291]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager swap '
Apr 18 12:26:34 hostname python[12381]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arg
Apr 18 12:26:35 hostname python[12488]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active c
Apr 18 12:26:36 hostname python[12662]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 fbalak-usm1
Apr 18 12:26:37 hostname python[12670]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager cpu '{
Apr 18 12:26:37 hostname python[12741]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arg
Apr 18 12:26:38 hostname python[12827]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active c
Apr 18 12:26:39 hostname python[12932]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 fbalak-usm1
Apr 18 12:26:40 hostname python[13005]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager mount_
Apr 18 12:26:41 hostname python[13099]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arg
Apr 18 12:26:41 hostname python[13161]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active c
Apr 18 12:30:21 hostname systemd[1]: Stopping Daemon to manage tendrl node monitoring...
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: Finding flows in namespace.tendrl.objectTraceback (most recent call last):
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 133, in handle
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: self.handler(*self.args, **self.kwargs)
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: File "/usr/lib/python2.7/site-packages/tendrl/node_monitoring/manager/__init__.py", 
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: Event(
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: NameError: global name 'Event' is not defined
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: s.Platform.flows
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: Registering object namespace.tendrl.objects.Service
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: Finding atoms in namespace.tendrl.objects.Service.atoms
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: Registering atom namespace.tendrl.objects.Service.atoms.BaseAtomRegistering atom nam
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: Registering object namespace.tendrl.objects.TendrlContext
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: Finding atoms in namespace.tendrl.objects.TendrlContext.atoms
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: Finding flows in namespace.tendrl.objects.TendrlContext.flows
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: Finding flows in namespace.tendrl.flowsRegistering flow namespace.tendrl.flows.Autho
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: File "/usr/bin/tendrl-node-monitoring", line 9, in <module>
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: load_entry_point('tendrl-node-monitoring==1.2.2', 'console_scripts', 'tendrl-node-mo
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: File "/usr/lib/python2.7/site-packages/tendrl/node_monitoring/manager/__init__.py", 
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: complete.wait(timeout=1)
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: File "/usr/lib64/python2.7/site-packages/gevent/event.py", line 77, in wait
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: result = self.hub.switch()
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 331, in switch
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: return greenlet.switch(self)
Apr 18 12:30:21 hostname tendrl-node-monitoring[11058]: NameError: global name 'Event' is not defined
Apr 18 12:30:21 hostname systemd[1]: tendrl-node-monitoring.service: main process exited, code=exited, status=1/FAILURE
Apr 18 12:30:21 hostname systemd[1]: Stopped Daemon to manage tendrl node monitoring.
Apr 18 12:30:21 hostname systemd[1]: Unit tendrl-node-monitoring.service entered failed state.
Apr 18 12:30:21 hostname systemd[1]: tendrl-node-monitoring.service failed.
```

Tested with:
tendrl-node-monitoring-1.2.2-04_18_2017_04_25_03.noarch
tendrl-commons-1.2.3-04_18_2017_17_31_14.noarch
tendrl-node-agent-1.2.3-04_18_2017_02_22_22.noarch
tendrl-gluster-integration-1.2.3-04_18_2017_16_27_06.noarch

**Comment by anmolbabu** [comment]
@fbalak The PR to fix this has been merged. Please check if this is still relevant.

**Comment by fbalak** [comment]
Now is tendrl-node-monitoring inactive right after server installation and stays inactive even after cluster import. This is state of the service:
`# systemctl status tendrl-node-monitoring`
```
● tendrl-node-monitoring.service - Daemon to manage tendrl node monitoring
   Loaded: loaded (/usr/lib/systemd/system/tendrl-node-monitoring.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2017-04-20 12:59:57 UTC; 9min ago
 Main PID: 10974 (code=exited, status=0/SUCCESS)

Apr 20 12:59:57 hostname systemd[1]: Stopping Daemon to manage tendrl node monitoring...
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: s.Platform.flows
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.Service
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.Service.atoms
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Registering atom namespace.tendrl.objects.Service.atoms.BaseAtomRegistering atom namespace.tendrl.objects.Service.atoms.CheckServiceStatusFinding flows in namespace.tendrl.objects.Service.flows
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.TendrlContext
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.TendrlContext.atoms
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.TendrlContext.flows
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.flowsRegistering flow namespace.tendrl.flows.AuthorizeSshKeyRegistering flow namespace.tendrl.flows.CreateClusterRegistering flow namespace.tendrl.flows.ImportClusterRegistering flow namespace.tendrl.flows.SetupSshSetup Tendrl definitions (.yml) for namespace.tendrlValidating registered (.py) flows in namespace.tendrl.flowsValidating defined (.yml) flows in namespace.tendrl.flowsValidating registered (.py) objects in namespace.tendrl.objectsValidating defined (.yml) objects in namespace.tendrl.objectsSetup NodeContext for namespace. tendrlLoad definitions (.yml) for namespace.tendrl.objects.NodeContextSetup TendrlContext for namespace.tendrlLoad definitions (.yml) for namespace.tendrl.objects.TendrlContext
Apr 20 12:59:57 hostname systemd[1]: Stopped Daemon to manage tendrl node monitoring.
```

`# journalctl -u tendrl-node-monitoring`
```
-- Logs begin at Thu 2017-04-20 12:48:30 UTC, end at Thu 2017-04-20 13:09:58 UTC. --
Apr 20 12:55:08 hostname systemd[1]: Started Daemon to manage tendrl node monitoring.
Apr 20 12:55:08 hostname systemd[1]: Starting Daemon to manage tendrl node monitoring...
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Creating namespace.node_monitoring from source tendrl.node_monitoring
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: namespace.node_monitoring created!
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding objects in namespace.node_monitoring.objects
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.node_monitoring.objects.BaseObject
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.node_monitoring.objects.BaseObject.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.node_monitoring.objects.BaseObject.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.node_monitoring.objects.Config
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.node_monitoring.objects.Config.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.node_monitoring.objects.Config.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.node_monitoring.objects.Definition
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.node_monitoring.objects.Definition.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.node_monitoring.objects.Definition.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.node_monitoring.flowsRegistering flow namespace.node_monitoring.flows.BaseFlowRegistering flow namespace.node_monitoring.flows.ConfigureCollectdSetup Tendrl definitions (.yml) for namespace.node_monitoringValidating registered (.py) flows in namespace.node_monitoring.flowsValidating defined (.yml) flows in namespace.node_monitoring.flowsValidating registered (.py) objects in namespace.node_monitoring.objectsSetup Config for namespace.node_monitoringSetup Etcd Orm for namespace.node_monitoringCreating namespace.tendrl from source tendrl.commons
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: namespace.tendrl created!
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding objects in namespace.tendrl.objects
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.ClusterNodeContext
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.ClusterNodeContext.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.ClusterNodeContext.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.ClusterTendrlContext
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.ClusterTendrlContext.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.ClusterTendrlContext.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.Cpu
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.Cpu.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.Cpu.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.Definition
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.Definition.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.Definition.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.DetectedCluster
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.DetectedCluster.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.DetectedCluster.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.Disk
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.Disk.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.Disk.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.File
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.File.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering atom namespace.tendrl.objects.File.atoms.BaseAtomRegistering atom namespace.tendrl.objects.File.atoms.WriteFinding flows in namespace.tendrl.objects.File.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.Job
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.Job.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.Job.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.Memory
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.Memory.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.Memory.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.Node
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.Node.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering atom namespace.tendrl.objects.Node.atoms.BaseAtomRegistering atom namespace.tendrl.objects.Node.atoms.CheckNodeUpRegistering atom namespace.tendrl.objects.Node.atoms.BaseAtomRegistering atom namespace.tendrl.objects.Node.atoms.CmdFinding flows in namespace.tendrl.objects.Node.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.NodeContext
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.NodeContext.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.NodeContext.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.NodeNetwork
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.NodeNetwork.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.NodeNetwork.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.Os
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.Os.atoms
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.Os.flows
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.Platform
Apr 20 12:55:09 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.Platform.atoms
Apr 20 12:55:19 hostname python[11339]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 hostname removes=None creates=None _uses_shell=False
Apr 20 12:55:19 hostname python[11348]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager cpu '{"Failure": 90, "Warning": 80}' removes=None creates=None _uses_shell=False
Apr 20 12:55:20 hostname python[11374]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arguments= runlevel=default
Apr 20 12:55:21 hostname python[11409]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active collectd.service removes=None creates=None _uses_shell=False
Apr 20 12:55:23 hostname python[11523]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 hostname removes=None creates=None _uses_shell=False
Apr 20 12:55:24 hostname python[11533]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager collectd '{"master_name": "fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com", "interval": 600}' removes=None creates=None _uses_shell=False
Apr 20 12:55:26 hostname python[11547]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arguments= runlevel=default
Apr 20 12:55:27 hostname python[11578]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active collectd.service removes=None creates=None _uses_shell=False
Apr 20 12:55:28 hostname python[11642]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 hostname removes=None creates=None _uses_shell=False
Apr 20 12:55:28 hostname python[11650]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager dbpush '{"master_name": "fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com", "interval": 600}' removes=None creates=None _uses_shell=False
Apr 20 12:55:29 hostname python[11664]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arguments= runlevel=default
Apr 20 12:55:29 hostname python[11695]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active collectd.service removes=None creates=None _uses_shell=False
Apr 20 12:55:31 hostname python[11703]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 hostname removes=None creates=None _uses_shell=False
Apr 20 12:55:31 hostname python[11711]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager mount_point '{"Failure": 90, "Warning": 80}' removes=None creates=None _uses_shell=False
Apr 20 12:55:32 hostname python[11727]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arguments= runlevel=default
Apr 20 12:55:32 hostname python[11771]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active collectd.service removes=None creates=None _uses_shell=False
Apr 20 12:55:34 hostname python[11787]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 hostname removes=None creates=None _uses_shell=False
Apr 20 12:55:34 hostname python[11795]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager memory '{"Failure": 90, "Warning": 80}' removes=None creates=None _uses_shell=False
Apr 20 12:55:35 hostname python[11817]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arguments= runlevel=default
Apr 20 12:55:36 hostname python[11848]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active collectd.service removes=None creates=None _uses_shell=False
Apr 20 12:55:37 hostname python[11936]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=ping -c 1 hostname removes=None creates=None _uses_shell=False
Apr 20 12:55:38 hostname python[11958]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=config_manager swap '{"Failure": 70, "Warning": 50}' removes=None creates=None _uses_shell=False
Apr 20 12:55:38 hostname python[12007]: ansible-basic.py Invoked with name=collectd pattern=None enabled=None state=restarted sleep=None arguments= runlevel=default
Apr 20 12:55:39 hostname python[12093]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl is-active collectd.service removes=None creates=None _uses_shell=False
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objectTraceback (most recent call last):
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 327, in run
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: result = self._run(*self.args, **self.kwargs)
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: File "/usr/lib/python2.7/site-packages/tendrl/node_monitoring/sync/__init__.py", line 11, in _run
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: NS.central_store_thread.update_last_seen_at()
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: File "/usr/lib/python2.7/site-packages/tendrl/node_monitoring/central_store/__init__.py", line 18, in update_last_seen_at
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: tendrl_now().isoformat()
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 465, in write
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: response = self.api_execute(path, method, params=params)
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 874, in wrapper
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: return self._handle_server_response(response)
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 954, in _handle_server_response
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: etcd.EtcdError.handle(r)
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 304, in handle
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: raise exc(msg, payload)
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: EtcdException: Raft Internal Error : etcdserver: request timed out
Apr 20 12:58:10 hostname tendrl-node-monitoring[10974]: <NodeMonitoringSyncStateThread at 0x2ab9870> failed with EtcdException
Apr 20 12:59:57 hostname systemd[1]: Stopping Daemon to manage tendrl node monitoring...
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: s.Platform.flows
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.Service
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.Service.atoms
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Registering atom namespace.tendrl.objects.Service.atoms.BaseAtomRegistering atom namespace.tendrl.objects.Service.atoms.CheckServiceStatusFinding flows in namespace.tendrl.objects.Service.flows
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Registering object namespace.tendrl.objects.TendrlContext
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Finding atoms in namespace.tendrl.objects.TendrlContext.atoms
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.objects.TendrlContext.flows
Apr 20 12:59:57 hostname tendrl-node-monitoring[10974]: Finding flows in namespace.tendrl.flowsRegistering flow namespace.tendrl.flows.AuthorizeSshKeyRegistering flow namespace.tendrl.flows.CreateClusterRegistering flow namespace.tendrl.flows.ImportClusterRegistering flow namespace.tendrl.flows.SetupSshSetup Tendrl definitions (.yml) for namespace.tendrlValidating registered (.py) flows in namespace.tendrl.flowsValidating defined (.yml) flows in namespace.tendrl.flowsValidating registered (.py) objects in namespace.tendrl.objectsValidating defined (.yml) objects in namespace.tendrl.objectsSetup NodeContext for namespace. tendrlLoad definitions (.yml) for namespace.tendrl.objects.NodeContextSetup TendrlContext for namespace.tendrlLoad definitions (.yml) for namespace.tendrl.objects.TendrlContext
Apr 20 12:59:57 hostname systemd[1]: Stopped Daemon to manage tendrl node monitoring.
```

Tested with:
tendrl-node-monitoring-1.2.3-04_20_2017_04_25_04.noarch
tendrl-commons-1.2.3-04_20_2017_14_45_14.noarch
tendrl-node-agent-1.2.3-04_20_2017_00_01_06.noarch

**Comment by anmolbabu** [comment]
can you please confirm etcd server address in /etc/node-monitoring/node-monitoring.conf.yaml is correct

**Comment by fbalak** [comment]
Yes, in /etc/tendrl/node-monitoring/node-monitoring.conf.yaml is correctly set up etcd_port and etcd_connection.

**Comment by fbalak** [comment]
It seems working. --> closing
Tested with:
tendrl-node-monitoring-1.2.3-04_21_2017_04_25_03.noarch
tendrl-commons-1.2.3-04_21_2017_05_13_06.noarch
tendrl-node-agent-1.2.3-04_21_2017_01_02_49.noarch
tendrl-gluster-integration-1.2.3-04_21_2017_04_39_16.noarch
tendrl-performance-monitoring-1.2.3-04_21_2017_03_02_04.noarch
tendrl-api-1.2.3-04_21_2017_01_58_24.noarch
